server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/power_shop_user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: 123456

loginType: JSON